/*PROYECTO FINAL
; *FUNDAMENTOS DE MICROPROCESADORES
; *
; *AUTOMATIZACIÓN DE CASAS, DOMÓTICA CON MICROCONTROLADOR AT89S52
; *
; *LUIS ALBERTO ANTÓN DELGADILLO
; *ERICK DE SANTIAGO ANAYA
; */

VALOR_CUENTA_M EQU 31H
CERRAR_ABRIR EQU P3.7

VALOR_RELOJ_L EQU 33H
VALOR_CUENTA_L EQU 34H
VECES_ARRIBA_L1 EQU 35H
VECES_ARRIBA_L2 EQU 36H
ARRIBA_L1 EQU 01H
ARRIBA_L2 EQU 02H
SENHAL1 EQU P3.6
SENHAL2 EQU P3.5

	ORG 00H
	JMP MAIN
	
	ORG 1BH
	JMP TIM_1
	
	ORG 2BH
	JMP TIM_2
	
	ORG 30H
MAIN: MOV IE, #10101000B
	MOV TMOD, #00100010B
	
	/* INICIALIZACION PARA FRECUENCIA MOTOR */
	MOV 0CBH, #HIGH(-20000)
	MOV 0CAH, #LOW(-20000)
	MOV 0CDH, #HIGH(-20000)
	MOV 0CCH, #LOW(-20000)
	MOV 0C8H, #00000100B
	MOV TH0, #-240
	MOV TL0, #-240
	MOV VALOR_CUENTA_M, #2	
	
	
	/* INICIALIZACION PARA FRECUENCIAS LEDS */
	MOV VALOR_RELOJ_L, #100D
	MOV VALOR_CUENTA_L, #200D
	SETB ARRIBA_L1
	SETB ARRIBA_L2
	MOV R2, VALOR_CUENTA_L
	MOV R1, VALOR_RELOJ_L
	LCALL COMP_A2
	MOV TH1, A
	MOV TL1, A	
	
	/* INICIALIZAR VALORES DE VECES EN ALTO LEDS */
	MOV VECES_ARRIBA_L1, #33D
	MOV VECES_ARRIBA_L2, #66D
	SETB TR1
	JMP $

TIM_2: SETB P0.0
	SETB TR0
	CLR 0CFH
CONTADOR: JNB TF0, $
	CLR TF0
	DJNZ VALOR_CUENTA_M, CONTADOR
	CLR P0.0
	JB CERRAR_ABRIR, ABRIR
	CERRAR: MOV VALOR_CUENTA_M, #6
	JMP FIN_TIM_1
	
	ABRIR: MOV VALOR_CUENTA_M, #2
	
	FIN_TIM_1: CLR TR0
		RETI

TIM_1: JNB ARRIBA_L1, COMPARA_LED_2
	DJNZ VECES_ARRIBA_L1, SIGUE_PERIODO_L
	CLR ARRIBA_L1
	CLR SENHAL1
	
	COMPARA_LED_2: JNB ARRIBA_L2, SIGUE_PERIODO_L
	DJNZ VECES_ARRIBA_L2, SIGUE_PERIODO_L
	CLR ARRIBA_L2
	CLR SENHAL2
	
	SIGUE_PERIODO_L: DJNZ R2, FIN_TIM_0
	MOV R2, VALOR_CUENTA_L
	SETB ARRIBA_L1
	SETB ARRIBA_L2
	SETB SENHAL1
	SETB SENHAL2
	MOV VECES_ARRIBA_L1, #33D
	MOV VECES_ARRIBA_L2, #66D
	
	FIN_TIM_0: RETI


COMP_A2: MOV A, R1
	CPL A
	INC A
	RET
	END
